doc(minimal-apis): Modify MinimalAPI doc
masastack/MASA.Docs pull request #12
Opened 2022-09-30 10:30 UTC by zhenlei520

# Description（描述）

Modify MinimalAPI doc

## Check list（检查列表）

_无需更改，仅供Code Reivewer作为标准参考_

- [x] 概念

- [x] 功能列表

- [ ] 环境准备（通用的可以参考快速入门文档中的，单个文档中只在与默认环境不同时才需指定，比如某个功能属于.NET 7的特性，而通用环境是.NET 6）

- [x] 使用，如果是增强类功能需提供对比参考突出优势

- [ ] 配置（如果有）

- [x] 高阶用法

- [ ] 性能测试（如果需要）

- [x] 原理剖析

- [x] 按照文档示例代码能够成功运行

- [x] 技术类名词提供出处或参考文献

- [x] 排版合理

2022-10-02 12:40 UTC, doddgu requested changes

2022-10-02 12:40 UTC, doddgu commented on docs/framework/contribs/service/minimal-apis.md
> +* 当版本为`null`或者空字符串时，此时 `var BaseUri = $"{前缀}/服务名(默认复数)"`
{前缀}/{服务名(默认复数)}

2022-10-02 12:40 UTC, doddgu commented on docs/framework/contribs/service/minimal-apis.md
> +* 当服务名为空字符串时，此时 `var BaseUri = $"{前缀}/版本"`
{前缀}/{版本}

2022-10-02 12:40 UTC, doddgu commented on docs/framework/contribs/service/minimal-apis.md
> +## 相关issues
Issues

2022-10-08 01:22 UTC, zhenlei520 commented on docs/framework/contribs/service/minimal-apis.md
> +| AutoAppendId  | 路由中是否包含{Id},例如: /api/v1/user/{id} | `true` |
不区分请求类型，未禁用AppendId且参数包含id的会增加{id}

2022-10-08 01:26 UTC, merged