feat:completed quickly start doc
masastack/MASA.Docs pull request #146
Opened 2023-03-31 12:19 UTC by MapleWithoutWords

2023-04-03 05:16 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +​		本章是一个 **Masa Framework** 快速入门教程，我们会使用 **Masa Framework** 创建一个简单的待办事项应用程序。以下是程序最终运行效果：
Two Tabs?

2023-04-03 05:16 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +​		本章是一个 **Masa Framework** 快速入门教程，我们会使用 **Masa Framework** 创建一个简单的待办事项应用程序。以下是程序最终运行效果：
一个 **Masa Framework** 快速入门教程?

2023-04-03 05:18 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +* .Net版本：6.0+
.NET 版本：6.0 +

2023-04-03 05:23 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +![](https://img2023.cnblogs.com/blog/1525201/202303/1525201-20230328231628904-1957534939.png)
更换其它图床，比如：https://sm.ms 或者上传到masa stack

2023-04-03 05:24 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +![](https://img2023.cnblogs.com/blog/1525201/202303/1525201-20230328231628904-1957534939.png)
虽然标题不是必须的，但空值不太合适

2023-04-03 05:25 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +![111](https://img2023.cnblogs.com/blog/1525201/202303/1525201-20230329215836338-1165974933.png)
111？

2023-04-03 05:28 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +   我们的TodoApp整个业务大概需要有以下接口：
我们的TodoApp需要有以下接口：

2023-04-03 05:32 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +   我们在 ```Masa.TodoApp.Contracts``` 项目中创建我们所需要的Dto，之所以在这里创建是因为我们接口和Blazor可以共享数据模型，这样避免我们前端项目重新定义数据模型
我们在 ```Masa.TodoApp.Contracts``` 类库中创建我们所需要的Dto，它将与`Blazor`项目可以共享数据模型, 避免多次定义

2023-04-03 05:34 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +> 在这里我们使用一个CQRS来完成我们业务层，在CQRS模式中我们的查询和其它业务操作是分开的。不了解CQRS的可以看看这篇文章：https://learn.microsoft.com/zh-cn/azure/architecture/patterns/cqrs
使用一个CQRS来完成我们业务层？

2023-04-03 05:35 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +### 创建CQRS业务服务
使用CQRS模式？

2023-04-03 05:38 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +3. 然后在 **Application**目录中创建我们的指令处理类： ```TodoQueryHandler.cs``` 和```TodoCommandHandler.cs```
然后在 **Application**目录中创建```TodoQueryHandler.cs``` 和```TodoCommandHandler.cs```类来处理应用程序所发送的命令

2023-04-03 05:44 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +        var todo = await _todoDbContext.Set<TodoEntity>().AsNoTracking().FirstOrDefaultAsync(t => t.Title == title && t.Id != id);
Any?

2023-04-03 05:45 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +        var todo = await _todoDbContext.Set<TodoEntity>().AsNoTracking().FirstOrDefaultAsync(t => t.Title == title && t.Id != id);
Remove AsNoTracking()

2023-04-03 05:45 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +在```Masa.TodoApp.WebApi```  项目下的 **Services**目录中创建一个**TodoService.cs**接口服务
类库下

2023-04-03 05:47 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +using Microsoft.EntityFrameworkCore;
sort

2023-04-03 05:47 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +using Masa.TodoApp.WebApi.Entities;
using sort

2023-04-03 05:51 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/overview/zh-CN.md
> +下一步就是添加我们的**Masa.Blazor**服务以及后端接口调用服务，修改 ```Masa.TodoApp.WebBalzor``` 项目中的```Program.cs```文件
添加**Masa.Blazor**服务?

2023-04-20 07:53 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +1. 在目录下使用cmd运行以下命令，它将会创建整个TodoApp解决方案。在这里我们将使用 [MASA.Blazor](https://docs.masastack.com/blazor/getting-started/installation)来完成我们UI界面。
这里为啥有个1，但是没有2

2023-04-20 07:53 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +我们在```TodoApp.Service```  项目下的**DataAccess/Entities**文件夹中定义一个```TodoEntity```实体类。
行类的这个应该是建议用单个`  ?  三个多用于多行的code？

2023-04-20 07:53 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   ![实体目录结构](https://masa-cdn-dev.oss-cn-hangzhou.aliyuncs.com/create_entity_effect.png)
这个域名需要更换使用统一的地址

2023-04-21 11:15 UTC, doddgu requested changes

2023-04-23 05:47 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
>  2. 在`TodoApp.Service`  项目下的 **Application\Queries**目录中创建我们的查询命令：`TodoGetListQuery.cs`
保持风格一致，与汉字保持一个空格距离

2023-04-23 05:48 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
>  3. 然后在 Application目录中创建TodoQueryHandler.cs 和TodoCommandHandler.cs类来处理应用程序所发送的命令
保持风格一致，与汉字保持一个空格距离

2023-04-23 05:48 UTC, xyfy commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
>  在 `TodoApp.Web` 项目下的**ApiCallers**目录中分别创建`TodoServiceOptions.cs`和`TodoCaller.cs`，前者是todo后端服务的配置，后者是接口调用
保持风格一致，与汉字保持一个空格距离

2023-04-23 11:19 UTC, doddgu requested changes

2023-04-23 11:19 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   dotnet new --install Masa.Template
6+的--install改成install了

2023-04-23 11:19 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +在目录下使用cmd运行以下命令，它将会创建整个TodoApp解决方案。在这里我们将使用 [MASA.Blazor](https://docs.masastack.com/blazor/getting-started/installation)来完成我们UI界面。
来完成我们UI界面前面加个空格保持一致

2023-04-23 11:19 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   dotnet new masafxsp --name TodoApp --no-https true --no-example true -db sqlite
masafxsp?

2023-04-23 11:19 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +    namespace TodoApp.Service.DataAccess;
多了一个空格

2023-04-23 11:24 UTC, doddgu requested changes

2023-04-23 11:24 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   :::: code-group
渲染后第一个标签页前面多空了一个位置出来

2023-04-23 11:24 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   using TodoApp.Web.ApiCallers;
我们的文档站点已经支持 diff 和 highlight line。

2023-04-23 14:03 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   :::: code-group
哪个多出空格，看不出来0-0

2023-04-23 14:03 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   using TodoApp.Web.ApiCallers;
![image](https://user-images.githubusercontent.com/38368335/233844331-a5f6b863-34cf-4532-994e-1368f50f6939.png)

2023-04-23 14:04 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   :::: code-group
![image](https://user-images.githubusercontent.com/38368335/233844362-c60a99be-3d0b-4aea-943c-4dde092ad4fe.png)
他能正常显示

2023-04-24 03:49 UTC, doddgu commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   using TodoApp.Web.ApiCallers;
Just use highlight line.

2023-04-24 05:39 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/getting-started/web-project/zh-CN.md
> +   :::: code-group
![image](https://user-images.githubusercontent.com/38368335/233908384-f476d01f-2e7a-4a81-b664-f970e790c5eb.png)
![image](https://user-images.githubusercontent.com/38368335/233908397-64c6ca11-d263-44ed-8bf5-fdcb11b5511c.png)
分辨率比较小的时候，code-group会出现滚动条。导致看起来标题距离左边有个空隙，怪怪的。建议有滚动条的时候不要隐藏图标，可以将图标颜色变下。可以点击的颜色就亮一点，不能点击的就暗淡点。 @capdiem

2023-04-24 05:48 UTC, doddgu approved these changes

2023-04-24 05:48 UTC, merged