docs(stack-alert) : Supplementary Development Guidelines and SDK Examples
masastack/MASA.Docs pull request #163
Opened 2023-04-19 09:55 UTC by wzh425

2023-04-19 10:37 UTC, zhenlei520 requested changes

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +### 可观测性接入
1级标题

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +### 告警处理第三方接入
2级标题

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
>  var builder = WebApplication.CreateBuilder(args);
使用新增加功能path，用于标记当前文件路径

![image](https://user-images.githubusercontent.com/9740886/233046735-00c4dc5c-3cbc-48a6-9ed8-21c34e8fd50d.png)

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +```csharp
代码块缩进 （请检查所有alert相关文档）

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/faq/zh-CN.md
>  ### Q：支持哪些通知渠道？
2级标题

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/faq/zh-CN.md
>  ### Q：告警中心适用于哪些人员？
2级标题

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
增加1级标题

2023-04-19 10:37 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
> +### 服务介绍
2级标题，后续标题依次更改

2023-04-19 10:38 UTC, capdiem requested changes

2023-04-19 10:38 UTC, capdiem commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +### 可观测性接入
为什么要跳过二级标题？

2023-04-19 10:38 UTC, capdiem commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +请参考[使用指南-WebHook](stack/alert/use-guide/web-hook#创建/编辑)
```suggestion
请参考[WebHook](stack/alert/use-guide/web-hook#创建/编辑)
```

不用层级吧，感觉没必要，不整洁。

2023-04-19 10:38 UTC, capdiem commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
> +```
这事什么格式，这个能高亮？

2023-04-19 10:38 UTC, capdiem commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
> +1. MASA.Scheduler Job需要告警时通过调用MASA.Alert的SDK自动创建告警规则并进行管理。
```suggestion
MASA.Scheduler Job需要告警时通过调用MASA.Alert的SDK自动创建告警规则并进行管理。
```

2023-04-19 11:43 UTC, wzh425 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
> +```
├──没有其他作用 仅用于表示层级

2023-04-20 02:21 UTC, capdiem requested changes

2023-04-20 02:21 UTC, capdiem commented on src/Masa.Stack.Docs/wwwroot/pages/alert/use-guide/alarm-rule/zh-CN.md
这里和下面都不用缩进吧

2023-04-20 07:27 UTC, wzh425 commented
@capdiem  已调整

2023-04-20 07:49 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/alert/develop-guide/zh-CN.md
> +   Install-Package Masa.Contrib.StackSdks.Tsc
建议使用dotnet  add package ,毕竟   install-package 依赖powershell，不适合跨平台

2023-04-20 07:49 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/alert/introduce/zh-CN.md
> +1. 可以争对所需要的业务对象进行日志监控，并设置告警规则，触发告警。
错别字  争

2023-04-20 07:49 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/alert/sdk-instance/zh-CN.md
> +示例只介绍部分参数用法
段落前后建议空行

2023-04-20 08:04 UTC, wzh425 commented
@xyfy  已调整

2023-04-20 11:27 UTC, capdiem commented
@wzh425 文档内容以后不用让我审

2023-04-21 06:28 UTC, xie1wei2 approved these changes

2023-04-21 06:38 UTC, zhenlei520 requested changes

2023-04-21 06:38 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/alert/introduce/zh-CN.md
> +# 介绍
产品介绍

2023-04-21 06:38 UTC, capdiem approved these changes

2023-04-21 06:43 UTC, zhenlei520 approved these changes
LGTM

2023-04-21 06:43 UTC, merged