fix:update dcc docs
masastack/MASA.Docs pull request #164
Opened 2023-04-20 06:03 UTC by kogel-net

# Description（描述）

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]

## Check list（检查列表）

_无需更改，仅供Code Reivewer作为标准参考_

- [ ] 概念

- [ ] 功能列表

- [ ] 环境准备（通用的可以参考快速入门文档中的，单个文档中只在与默认环境不同时才需指定，比如某个功能属于.NET 7的特性，而通用环境是.NET 6）

- [ ] 使用，如果是增强类功能需提供对比参考突出优势

- [ ] 配置（如果有）

- [ ] 高阶用法

- [ ] 性能测试（如果需要）

- [ ] 原理剖析

- [ ] 按照文档示例代码能够成功运行

- [ ] 技术类名词提供出处或参考文献

- [ ] 排版合理

2023-04-20 07:32 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/basic-concepts/zh-CN.md
> +### 1. 简介
使用丝滑的标题顺序。。。不要从1级跳到三级

2023-04-20 08:17 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
> +   1. 通过发布历史回滚
个人不建议没有先后顺序的列表使用数字序号来标记

2023-04-24 12:48 UTC, zhenlei520 requested changes

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/basic-concepts/zh-CN.md
> +## 1. 简介
If the title is not necessary, try not to add serial numbers

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +通过DCC扩展IConfiguration管理远程配置的能力。而这不单依赖于`DCC的SDK`，还需要依赖MasaConfiguration。MasaConfiguration把配置分为本地节点和远程节点，而DCC就是远程节点。
Leave a space on the left and right in English

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
>  ```powershelll
shell

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   ```appsettings.json
json appsettings.json

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   using Microsoft.AspNetCore.Mvc;
global using sort

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   [Route("[controller]")]
``` csharp
[Route("[action]")]
```
or 
```csharp
[Route("[controller]/[action]")]
```

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +> 此类需要继承`ConfigurationApiMasaConfigurationOptions`，如果没有继承需要手动映射
blank line

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   ``` powershell
shell

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +    Install-Package Masa.Contrib.StackSdks.Dcc
dotnet  add package Masa.Contrib.StackSdks.Dcc

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +    Install-Package Masa.Contrib.StackSdks.Dcc
more than one space

2023-04-24 12:48 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   [Route("[controller]")]
``` csharp
[Route("[action]")]
```
or 
```csharp
[Route("[controller]/[action]")]
```

2023-04-25 06:08 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/basic-concepts/zh-CN.md
>  参考：[MASA.PM环境介绍](stack/pm/basic-concepts)
全文风格统一，英文与汉字之间保留一个空格

2023-04-25 06:08 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/basic-concepts/zh-CN.md
>  MASA.DCC是一个分布式配置中心系统。随着系统越做越大，服务越来越多，每个服务可能在不同的环境集群中，这时候避免不了去使用配置中心去统一管理我们的配置文件，而MASA.DCC就是个不错的选择，其核心功能依赖于Redis，可做到客户端与Redis直接进行交互，不过度依赖服务端。
全文风格统一，英文与汉字之间保留一个空格，通查全文

2023-04-25 06:08 UTC, xyfy commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
> +### 1. 创建配置对象
尽量标题里不使用序号，如果使用序号，可以考虑不让它成为标题

2023-04-25 07:43 UTC, zhenlei520 requested changes
Closed issues need to be rechecked

2023-04-25 07:43 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
>     1. 点击全景页面项目下的应用进入配置详情页
extra spaces

2023-04-25 07:43 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
> +      ![](https://cdn.masastack.com/stack/doc/dcc/rc1/config.png)
Just keep 3 spaces

2023-04-25 07:43 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
>     1. 点击全景页面项目下的应用进入配置详情页
The same is true below

2023-04-25 07:43 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +### 1.入门
1？

2023-04-25 07:46 UTC, zhenlei520 requested changes

2023-04-25 07:46 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   ```json
json appsettings.json

2023-04-25 07:46 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +   ```csharp
csharp Program.cs

2023-04-27 08:00 UTC, zhenlei520 commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/sdk-instance/zh-CN.md
> +此处Redis为远程配置，介绍的是远程配置挂载到 `IConfiguration` 之后的效果以及用法，此配置与`MASA.Contrib.Configuration` 中 `Redis` 的毫无关系，仅仅是展示同一个配置信息在两个源的使用方式以及映射节点关系的差别
@MayueCif plan

2023-04-28 03:52 UTC, zhenlei520 approved these changes
LGTM @MayueCif

2023-04-28 11:20 UTC, MayueCif commented on src/Masa.Stack.Docs/wwwroot/pages/dcc/get-started/zh-CN.md
> +   - 格式（Json、Xml、Yaml、Properties、Raw。该文档以 Json 格式为大家演示）
大写

2023-04-28 11:33 UTC, merged