feat:optimize cache article
masastack/MASA.Docs pull request #172
Opened 2023-04-21 09:28 UTC by MapleWithoutWords

2023-04-21 10:49 UTC, zhenlei520 requested changes

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +多级缓存是指在一个系统的不同架构层级进行数据缓存，以提升访问效率。MASA Framework的多级缓存是在分布式缓存的基础上，再加了一层内存缓存。使用多级缓存, 可以降低请求穿透到分布式缓存, 减少网络消耗以及序列化带来的性能影响, 使用它可以大大缩减响应时间。并且MASA Framework的多级缓存是支持分布式部署的，当缓存数据在集群的某个节点被更新或删除时，其它集群节点也会同步更新或删除
MASA Framework 左右空一格，后续所有英文左右都留一个空格

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +## 介绍
统一为 概述

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +      ```shell
shell 终端

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +      ```csharp Program.cs
检查排版

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +       distributedCacheOptions.UseStackExchangeRedisCache(RedisConfigurationOptions);
需要传入具体`Redis`配置对象

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +   ![多级缓存原理流程图](https://masa-cdn-dev.oss-cn-hangzhou.aliyuncs.com/multilevel_cache.png)
多级缓存中多增加一个说明，告知用户使用多级缓存的弊端，有哪些需要注意的问题

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/overview/zh-CN.md
> +   * 超高频繁访问的数据，数据库读取缓慢。
第二点重复

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/overview/zh-CN.md
> +MASA Framework中的缓存组件提供[分布式缓存](/framework/building-blocks/caching/stackexchange-redis)、[多级缓存](/framework/building-blocks/caching/multilevel-cache)的支持。并且分布式缓存和多级缓存分为抽象的构建块和默认的实现，我们的程序只需要依赖抽象的构建块就可以了，默认
提供了分布式缓存、多级缓存能力，并且为它们提供了默认实现

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +## 介绍
概述

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +2. 修改appsettings.json文件，添加`Redis`的配置信息
添加 `Redis` 配置信息

> 修改某个文件不再重复，在代码块上指定路径即可

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +3. 添加分布式缓存配置，并使用Redis缓存
这个是属于注册服务，并不属于添加配置

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +1. 可以对Key进行分类，可以使用模糊查询查询这一类型的所有数据。
这块可以弱化

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +2. 不同系统中缓存相同id作为Key，但是数据却不同的时候，我们给每个Key增加数据类型前缀，就可以达到互不干扰的作用。
优点应该是写起来更省事，具体是如何做的？`前缀+key`

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +        //设置key的有效期是30分钟
超过30分钟缓存过期

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +        //设置滑动过期时间为10分钟，10分钟之内key如果被访问了，则再延长10分钟过期，直到30分钟过后过期则不再延长。
当该缓存Key在10分钟之内被访问了，则继续延长10分钟 （直到达到绝对过期时间后被删除）

若该缓存key在10分钟内未被访问，则会被移除。

2023-04-21 10:49 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +简单来说：当设置缓存的时候，设置滑动时间为过期时间，每次获取缓存数据的时候重新计算过期时间。因此当缓存超过设置的滑动过期时间后, 缓存会被删除, 当在滑动过期时间内时, 会重新计算过期时间并更新。
过期时间为：绝对过期时间与滑动过期时间中取最小值

2023-04-23 02:10 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +1. 可以对Key进行分类，可以使用模糊查询查询这一类型的所有数据。
这块弱化之后，啥都不写吗？

2023-04-23 04:06 UTC, zhenlei520 requested changes

2023-04-23 04:06 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/multilevel-cache/zh-CN.md
> +   ### 同步更新
不需要空格，下面同样问题

2023-04-23 04:06 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> + [Route("[controller]")]
[Route("[controller]/[action]")]

2023-04-23 04:06 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +#### 3. 通过委托指定Redis配置注册
Redis两边空一格

2023-04-23 04:06 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +::: code-group-item 2. 指定`Configuration`注册分布式Redis缓存
目前code-group title不支持使用markdown语法，确保不使用markdown语法或者提个issues支持它

2023-04-23 04:06 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caching/stackexchange-redis/zh-CN.md
> +[Route("[controller]")]
`[Route("[controller]/[action]")]`

2023-04-23 07:44 UTC, zhenlei520 approved these changes
LGTM

2023-04-23 07:44 UTC, merged