doc:optimize service caller article
masastack/MASA.Docs pull request #177
Opened 2023-04-23 13:38 UTC by MapleWithoutWords

# Description（描述）

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]

## Check list（检查列表）

_无需更改，仅供Code Reivewer作为标准参考_

- [ ] 概念

- [ ] 功能列表

- [ ] 环境准备（通用的可以参考快速入门文档中的，单个文档中只在与默认环境不同时才需指定，比如某个功能属于.NET 7的特性，而通用环境是.NET 6）

- [ ] 使用，如果是增强类功能需提供对比参考突出优势

- [ ] 配置（如果有）

- [ ] 高阶用法

- [ ] 性能测试（如果需要）

- [ ] 原理剖析

- [ ] 按照文档示例代码能够成功运行

- [ ] 技术类名词提供出处或参考文献

- [ ] 排版合理

2023-04-24 13:39 UTC, zhenlei520 requested changes

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +基于[DaprClient](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/dotnet-daprclient-usage/)实现的服务调用
基于 [DaprClient](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-client/dotnet-daprclient-usage/) 实现的服务调用

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
>  ``` powershell
shell 终端

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +2. 修改 `Program.cs` 类，推荐使用 `AddAutoRegistrationCaller` 自动注册服务调用
推荐使用 `AddAutoRegistrationCaller` 自动注册服务调用

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +```csharp
csharp Program.cs

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +> 默认AddCaller(func)注册的Name为空字符串, 可直接构造函数注入使用 ICaller。如果制定了Name名称，则需要通过 `ICallerFactory` 提供的 `Create` 方法获得
默认 AddCaller(func) 注册的 Name 为空字符串

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 使用 AddCaller 方法注册服务调用。不指定 Name 时，Name为空
Name 为空

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +        daprClientBuilder.UseHttpEndpoint("http://localhost:3500");
This is not recommended, it is recommended to use environment variables to set HttpPort, gRPC Port

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +```csharp TraceMiddleware.cs
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +当 **被调用的服务** 也需要身份认证的时候，我们可以使用服务调用的身份认证，将当前请求的认证信息传递到 **被调用的服务**。MASA Framework中服务调用的身份认证同时支持 **ASP.Net Core** 项目以及 **Blazor Server** 项目
以及 **Blazor** 项目

> Blazor WebAssembly也支持

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +``` powershell
shell 终端

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 在我们的项目中安装 ```Masa.Contrib.Service.Caller.Authentication.AspNetCore``` 包
\`Masa.Contrib.Service.Caller.Authentication.AspNetCore\`

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 在我们的Blazor项目中安装 ```Masa.Contrib.Service.Caller.Authentication.Standard``` 包
\'Masa.Contrib.Service.Caller.Authentication.Standard\'

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/overview/zh-CN.md
> +## 功能列表
最佳实践

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +基于 [.NET Core 的 HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-8.0) 实现的服务调用
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
>  ``` powershell
shell 终端

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +2. 修改 `Program.cs` 类，推荐使用 `AddAutoRegistrationCaller` 自动注册服务调用
使用 `AddAutoRegistrationCaller` 自动注册服务调用

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```csharp
csharp Program.cs

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +3. 新建类 `UserCaller.cs`，并继承 **HttpClientCallerBase**。（你也可以将 `BaseAddress` 的值放到 `appsettings.json` 配置文件中，请看[注册多个服务](#注册多个服务)）
The title is not too long

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +3. 新建类 `UserCaller.cs`，并继承 **HttpClientCallerBase**。（你也可以将 `BaseAddress` 的值放到 `appsettings.json` 配置文件中，请看[注册多个服务](#注册多个服务)）
> 你也可以将 `BaseAddress` 的值放到 `appsettings.json` 配置文件中，请看[注册多个服务](#注册多个服务)

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +> 默认AddCaller(func)注册的Name为空字符串, 可直接构造函数注入使用 ICaller。如果制定了Name名称，则需要通过 `ICallerFactory` 提供的 `Create` 方法获得
默认 AddCaller(func) 注册的 Name 为空字符串

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +> 默认AddCaller(func)注册的Name为空字符串, 可直接构造函数注入使用 ICaller。如果制定了Name名称，则需要通过 `ICallerFactory` 提供的 `Create` 方法获得
如果制定了 Name 名称

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```csharp ServiceCallerOptions.cs
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```csharp
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +``` powershell
shell 终端

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +``` powershell
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +``` powershell
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +``` powershell
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```razor
razor  App.razor

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```csharp
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +1. 新增认证服务, 并实现`IAuthenticationService`
并实现 `IAuthenticationService`

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +:::: code-group
missing spaces

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +如果你希望设置超时时间, 默认请求头等信息, 则可通过重写`HttpClientCallerBase`提供的`ConfigureHttpClient`方法, 例如:
重写 `HttpClientCallerBase` 提供的 `ConfigureHttpClient` 方法

2023-04-24 13:39 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
>  ```csharp
missing spaces

2023-04-26 02:45 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +> 默认AddCaller(func)注册的Name为空字符串, 可直接构造函数注入使用 ICaller。如果制定了Name名称，则需要通过 `ICallerFactory` 提供的 `Create` 方法获得
> 如果制定了 Name 名称

是指定吧

2023-04-26 10:40 UTC, zhenlei520 requested changes

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +### 修改Dapr端口
修改 Dapr 端口

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +   ``` powershell
shell 终端

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +   ::: code-group-item 自动注册的Caller
自动注册

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +   ::: code-group-item 手动注册的Caller
手动注册

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 新增认证服务, 并实现`IAuthenticationService`
并实现 `IAuthenticationService`

空格

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +   ::: code-group-item 自动注册的Caller
自动注册

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 新建支持Yaml的RequestMessage、ResponseMessage, 并分别实现IRequestMessage、IResponseMessage
新建支持 `Yaml `

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +1. 新建支持Yaml的RequestMessage、ResponseMessage, 并分别实现IRequestMessage、IResponseMessage
空格

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +```csharp Program.cs
格式化 3个空格

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +2. 修改 `Program.cs` 文件，注册服务调用，使用 `Configure` 初始化 `ServiceCallerOptions` 配置。并在 `appsettings.json` 文件下新增我们的配置节点
简单描述，path改到代码块上

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +1. 在项目中安装`Masa.Contrib.Service.Caller.Serialization.Xml`
空格

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +   ::: code-group-item 手动注册的Caller
手动注册

2023-04-26 10:40 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> +   ::: code-group-item 自动注册的Caller
自动注册

2023-04-26 10:45 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +### 修改Dapr端口
加空格，好像没法导航

2023-04-27 07:26 UTC, zhenlei520 requested changes

2023-04-27 07:26 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/daprclient/zh-CN.md
> +   ```csharp
l:1,3,6

2023-04-27 07:26 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/caller/httpclient/zh-CN.md
> -## 常见问题
Migrate to FAQs

2023-04-28 11:00 UTC, MayueCif approved these changes

2023-04-28 11:17 UTC, zhenlei520 approved these changes

2023-04-28 11:17 UTC, merged