doc:optimize configuration article
masastack/MASA.Docs pull request #197
Opened 2023-04-26 14:33 UTC by MapleWithoutWords

# Description（描述）

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]

## Check list（检查列表）

_无需更改，仅供Code Reivewer作为标准参考_

- [ ] 概念

- [ ] 功能列表

- [ ] 环境准备（通用的可以参考快速入门文档中的，单个文档中只在与默认环境不同时才需指定，比如某个功能属于.NET 7的特性，而通用环境是.NET 6）

- [ ] 使用，如果是增强类功能需提供对比参考突出优势

- [ ] 配置（如果有）

- [ ] 高阶用法

- [ ] 性能测试（如果需要）

- [ ] 原理剖析

- [ ] 按照文档示例代码能够成功运行

- [ ] 技术类名词提供出处或参考文献

- [ ] 排版合理

2023-04-27 07:13 UTC, zhenlei520 requested changes

2023-04-27 07:13 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/dcc/zh-CN.md
> +           return await _configurationApiClient.GetAsync<AppConfig>("AppConfig", newvalue =>
This example is not recommended, OnChange is generally used in singleton services

2023-04-27 07:13 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/dcc/zh-CN.md
> +           return await _configurationApiClient.GetAsync<AppConfig>("enviroment", "cluster", "appId", "AppConfig", newvalue =>
same as above

2023-04-27 07:17 UTC, zhenlei520 requested changes

2023-04-27 07:17 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/configuration-local/zh-CN.md
> +本地配置也是基于 `Microsoft.Extensions.Configuration` 来实现的，所以它也支持 [.NET Core的 Options 模式](https://learn.microsoft.com/zh-cn/dotnet/core/extensions/options)
.NET Core 的

2023-04-27 07:17 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/configuration-local/zh-CN.md
> +   ```csharp AppConfig.cs l:3
l:1,3

2023-04-27 07:17 UTC, zhenlei520 commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/configuration-local/zh-CN.md
> +   ```csharp Program.cs
l:3-6

2023-04-27 08:10 UTC, MapleWithoutWords commented on src/Masa.Framework.Docs/wwwroot/pages/building-blocks/configuration/configuration-local/zh-CN.md
> +public class AppConfig : LocalMasaConfigurationOptions
这个例子是说如果我们用了MasaConfiguration，还想通过IConfiguration去获取配置的时候，那么必须加上Local

2023-04-28 11:15 UTC, MayueCif approved these changes

2023-04-28 11:17 UTC, zhenlei520 approved these changes

2023-04-28 11:17 UTC, merged