feat: add prometheus and observability docs
masastack/MASA.Docs pull request #25
Opened 2022-12-15 01:11 UTC by Qinyouzeng

2022-12-20 10:55 UTC, doddgu requested changes

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +我们基于[Opentelemetry](https://opentelemetry.io/docs/)的可观测性接入，使用标准的OTLPExporter，[Logs](https://opentelemetry.io/docs/concepts/observability-primer/#logs)和[Traces](https://opentelemetry.io/docs/concepts/
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> + 当前只集成了`Opentelemetry`，采集的`Metric`范围较少，可以根据需求，添加第三方更为成熟的`Metric`监测库，或自定义添加，可参考[Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics)
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +当前主要集成了http和DataBase(EF core模式)链路追踪，链路相关详细资料可参见[Distributed tracing](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)和[Collect a distributed trace](https://learn.microso
EF Core

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +当前主要集成了http和DataBase(EF core模式)链路追踪，链路相关详细资料可参见[Distributed tracing](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)和[Collect a distributed trace](https://learn.microso
http -> HTTP

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +通过集成`Opentelemetry`后，直接使用[ILogger](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line)记录日志，日志或自动与相关的trace相关联，在通过相关日志排查问题时，可以根据链路traceId查找相关的链路信息，更利于问题排查。
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +通过集成`Opentelemetry`后，直接使用[ILogger](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line)记录日志，日志或自动与相关的trace相关联，在通过相关日志排查问题时，可以根据链路traceId查找相关的链路信息，更利于问题排查。
traceId? TraceId?

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +通过集成`Opentelemetry`后，直接使用[ILogger](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line)记录日志，日志或自动与相关的trace相关联，在通过相关日志排查问题时，可以根据链路traceId查找相关的链路信息，更利于问题排查。
trace? Trace?

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +1. [更加便捷的集成Opentelemetry，收集可观性数据](#集成Opentelemetry)；
可观测性

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +1. [更加便捷的集成Opentelemetry，收集可观性数据](#集成Opentelemetry)；
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +    //环境，例如开发、测试、生产等，可不配置
可不配置 -> 可选配置

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +    //服务版本号，可不配置
可不配置 -> 可选配置，默认xxx

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +1. 如果想完全自定义可观测性的配置，可以参考[OpenTelemetry for netcore](https://opentelemetry.io/docs/instrumentation/net/getting-started/);
netcore -> ASP.NET Core

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +    //balzor应用和api应用在链路的过滤执行条件上有区别
blazor

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +`resourceBuilder`创建参考[Log](#log)，此处需要明确下，由于在netcore6.0中，[基于`SignalR`的长链接，在链路处理上存在无法区分链路的问题](https://github.com/dotnet/aspnetcore/issues/29846)，当前我们采用了忽略长链接的链路，后续官方版本升级时，我们也会跟进和修正该问题。
netcore 6.0 -> .NET 6

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +该示例集成了`Opentelemetry`并添加了`RuntimeMetrics`运行时`metric`监测，如果需要添加其它`metrics`的监测，自己引入包添加监测即可。
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +#### Metric
Metric? Metrics?

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +1. `Task<PaginatedListBase<LogResponseDto>> ListAsync(BaseRequestDto query)`：日志列表分页查询，目前最大只能到第9999条数据，
Why max 9999?

2022-12-20 10:55 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +4. `void GetAll(BaseRequestDto query, Action<IEnumerable<TraceResponseDto>> resultAction)`：获取指定条件的所有trace数据
No real-time and batch settings.

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +APM 系统对于监视单体应用程序或传统分布式应用程序并对其进行故障排除非常有效，在这些应用程序中，新代码会定期发布，并且应用程序组件、服务器和相关资源之间的工作流和依赖关系是众所周知的或易于跟踪的。
APM系统？ APM 系统？

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +在过去时间里，IT 团队主要依靠 APM 和 NPM 来监控应用程序及其运行的网络并对其进行故障排除。
What's the concept of APM and NPM?

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +### 可观察性如何运作？
可观测性？可观察性？

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +应用程序可观察性系统通过与应用程序和基础架构组件中内置的现有仪器相集成，并通过提供工具将仪器添加到这些组件，不断发现和收集应用程序性能遥测数据。应用程序可观察性侧重于四种主要遥测类型、可观察性的三大支柱——`logs`、`metrics`和`traces`——以及依赖性。
可观测性？可观察性？ Twice!

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +网络可观察性系统采用类似的方法，通过从混合云环境收集一系列网络性能数据。这些数据包括来自路由器和交换机的指标，有助于了解它们的性能和健康状况，以及用于深入了解通过网络设备运行的应用程序的流数据，以及相关的元数据。
可观测性？可观察性？

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +许多应用程序可观察性系统会自动发现系统中可能出现的新遥测来源（例如对另一个软件应用程序的新 API 调用）。由于它们处理的数据比标准 APM 解决方案多得多，因此许多平台都包含 AIOps（运营人工智能）功能，可以从噪音（与问题无关的数据）中筛选出信号——实际问题的迹象。
可观测性？可观察性？

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +[`OpenTelemetry`](https://opentelemetry.io/)，也简称为`OTel`，是一个供应商中立、开源的可观察性框架，用于检测、生成、收集和导出遥测数据，如 `traces`、`metrics`和`logs`。作为一项行业标准，它受到许多供应商的原生支持。
可观测性？可观察性？

2022-12-20 10:55 UTC, doddgu commented on docs/framework/concepts/observability.md
> +### Opentelemtry
OpenTelemetry

2022-12-20 10:55 UTC, doddgu commented on docs/framework/utils/data/prometheus.md
> +var prometheusUrl="http://localhost:9090";
Format code.

2022-12-20 10:55 UTC, doddgu commented on docs/framework/utils/data/prometheus.md
> +
Remove the blank line.

2022-12-23 07:14 UTC, doddgu requested changes

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +当前主要集成了`Http`和`Database`(EF core模式)链路追踪，链路相关详细资料可参见[Distributed tracing](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)和[Collect a distributed trace](https://learn.mic
EF core -> EF Core

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +1. 如果想完全自定义可观测性的配置，可以参考[OpenTelemetry for netcore](https://OpenTelemetry.io/docs/instrumentation/net/getting-started/);
OpenTelemetry -> opentelemetry

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +> [OTLP服务相关部署和配置](https://OpenTelemetry.io/docs/collector/)
OpenTelemetry -> opentelemetry

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +我们可观测性基于[OpenTelemetry](https://OpenTelemetry.io/docs/)的接入，使用标准的OTLPExporter，[Logs](https://OpenTelemetry.io/docs/concepts/observability-primer/#logs)和[Traces](https://OpenTelemetry.io/docs/concepts/
url：OpenTelemetry -> opentelemetry

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +目前采用的标准[`Http api`](../utils/data/prometheus.md)，目前仅实现了几个常用的api。
api -> API

2022-12-23 07:14 UTC, doddgu commented on docs/framework/building-blocks/observability.md
> +`Logs`和`Traces`存储于`Elasticseach`,`Metrics`存储于`Prometheus`，所以目前版本的`Logs`和`Traces`的查询api也是基于`Elasticsearch`实现。另外使用该功能时，需要引入包：
api -> API

2022-12-26 03:52 UTC, Qinyouzeng commented on docs/framework/building-blocks/observability.md
> +4. `void GetAll(BaseRequestDto query, Action<IEnumerable<TraceResponseDto>> resultAction)`：获取指定条件的所有trace数据
`Traces` and `Logs` not has real-time and batch settings API, `Metrics` has these API.

2022-12-26 06:53 UTC, doddgu approved these changes
LGTM

2022-12-26 06:53 UTC, merged