feat: Add doc
masastack/MASA.Docs pull request #28
Opened 2022-12-22 03:20 UTC by zhenlei520

# Description（描述）

Add doc

## Check list（检查列表）

_无需更改，仅供Code Reivewer作为标准参考_

- [x] 概念

- [x] 功能列表

- [x] 环境准备（通用的可以参考快速入门文档中的，单个文档中只在与默认环境不同时才需指定，比如某个功能属于.NET 7的特性，而通用环境是.NET 6）

- [x] 配置（如果有）

- [x] 高阶用法

- [x] 按照文档示例代码能够成功运行

- [x] 技术类名词提供出处或参考文献

- [x] 排版合理

2022-12-23 08:14 UTC, doddgu requested changes

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/enums.md
> +[TestMethod]
TestMethod?

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/expressions.md
> +    condition = condition.And(false, i => i < 5);
Bad example

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/expressions.md
> +    condition = condition.Or(i => i < 1);
i < 2

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/expressions.md
> +    Assert.AreEqual(6, result[0]);
0 = 1
1 = 6
2 = 7

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* ChineseLetterNumber: 中文数字验证
中文字母数字

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* Phone: 手机号验证 (支持`zh-CN`、`en-US`、`en-GB`)
Difference?

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/security/token.md
> +title: 安全 - jwt加密与验证
jwt -> JWT

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/security/index.md
> +* [Token](/framework/utils/security/token): Jwt加密验证
Jwt -> JWT

2022-12-23 08:14 UTC, doddgu commented on docs/framework/utils/security/token.md
> +1.注册`Jwt`扩展
Jwt -> JWT

2022-12-23 08:14 UTC, doddgu commented on docs/stack/pm/guide/sdk-instance.md
>  ```c#
Missing a place to explain what our coding rules are, but it don't worry, just remember missing it enough.

2022-12-23 09:00 UTC, zhenlei520 commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* Phone: 手机号验证 (支持`zh-CN`、`en-US`、`en-GB`)
The mobile phone number rules in different countries are slightly different

please refer to https://blog.csdn.net/u012757419/article/details/117259918

2022-12-23 09:04 UTC, zhenlei520 commented on docs/framework/utils/extensions/dotnet.md
> +* [`String`类型扩展](#string)
It is not an extension of object. The extension class of StringExtensions is only `String`. As for the extension of `Object`, it will be gradually supported in the future as needed.

2022-12-23 09:35 UTC, zhenlei520 commented on docs/framework/building-blocks/r-w-spliting.md
> +* [中间件](/framework/contribs/dispatcher/event-bus)
Cross-page anchors cannot be used temporarily, unless absolute addresses are used, and later see if the new document site supports the function of cross-page anchors

2022-12-23 09:37 UTC, zhenlei520 commented on docs/framework/building-blocks/r-w-spliting.md
> +* [编排](/framework/contribs/dispatcher/event-bus)
Same as above

2022-12-23 09:38 UTC, zhenlei520 commented on docs/framework/utils/extensions/enums.md
> +[TestMethod]
It's a unit test and has been removed

2022-12-23 10:03 UTC, zhenlei520 commented on docs/framework/utils/extensions/expressions.md
> +    condition = condition.And(false, i => i < 5);
Processed

2022-12-23 10:13 UTC, zhenlei520 commented on docs/framework/building-blocks/data/mapping/index.md
> +public void Main()
Processed

2022-12-26 01:19 UTC, doddgu commented on docs/framework/utils/extensions/dotnet.md
> +* [`String`类型扩展](#string)
Why S and o?

2022-12-26 01:20 UTC, doddgu commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* Phone: 手机号验证 (支持`zh-CN`、`en-US`、`en-GB`)
You need to explain it

2022-12-26 01:54 UTC, zhenlei520 commented on docs/framework/utils/extensions/expressions.md
> +    condition = condition.And(false, i => i < 5);
Processed

2022-12-26 01:54 UTC, zhenlei520 commented on docs/framework/utils/extensions/dotnet.md
> +* [`String`类型扩展](#string)
Processed

2022-12-26 01:55 UTC, zhenlei520 commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* Phone: 手机号验证 (支持`zh-CN`、`en-US`、`en-GB`)
Processed

2022-12-26 05:20 UTC, doddgu requested changes

2022-12-26 05:20 UTC, doddgu commented on docs/framework/utils/extensions/validatios/fluent-validation.md
> +* Phone: 手机号验证 (支持`zh-CN`、`en-US`、`en-GB`)
Continue to change

2022-12-26 05:56 UTC, doddgu approved these changes
LGTM

2022-12-26 05:57 UTC, merged